import { supabase } from './app.js';
const $=id=>document.getElementById(id);let currentUser=null,captainTeam=null;
async function getUser(){const s=await supabase.auth.getSession();return s?.data?.session?.user||null}
async function loadCaptainTeam(){currentUser=await getUser();if(!currentUser){$('noTeamBox').style.display='block';return}
const {data,error}=await supabase.from('teams').select('*').eq('captain_id',currentUser.id).maybeSingle();if(error)throw error;
if(!data){$('noTeamBox').style.display='block';$('teamBox').style.display='none';return}
captainTeam=data;$('teamBox').style.display='block';$('noTeamBox').style.display='none';$('teamName').textContent=data.name||'Team';$('teamInfo').textContent='Team ID: '+data.id;if(data.logo_url)$('teamLogo').src=data.logo_url;$('teamStatus').textContent='Captain access confirmed.';await loadMembers();}
async function loadMembers(){const box=$('membersBox');const {data,error}=await supabase.from('team_memberships').select('*, profiles:profiles(id, username, display_name, riot_id, avatar_url)').eq('team_id',captainTeam.id).order('created_at',{ascending:true});if(error){box.textContent='Roster load error: '+error.message;return}
if(!data||!data.length){box.innerHTML='<p class="muted">No roster members yet.</p>';return}
box.innerHTML=data.map(m=>{const name=m.profiles?.display_name||m.profiles?.username||m.user_id||'Player';return `<div class="member-row" data-id="${m.id}"><div><strong>${name}</strong><br><span class="muted">${m.profiles?.riot_id||'Riot ID not set'}</span></div><select class="roleSelect">${['captain','player','substitute','coach'].map(r=>`<option value="${r}" ${m.role===r?'selected':''}>${r}</option>`).join('')}</select><button class="secondary removeBtn">Remove</button></div>`}).join('');
document.querySelectorAll('.member-row').forEach(row=>{row.querySelector('.roleSelect').addEventListener('change',async e=>{const {error}=await supabase.from('team_memberships').update({role:e.target.value}).eq('id',row.dataset.id);$('teamStatus').textContent=error?'Role update error: '+error.message:'Role updated.'});row.querySelector('.removeBtn').addEventListener('click',async()=>{if(!confirm('Remove this player from roster?'))return;const {error}=await supabase.from('team_memberships').delete().eq('id',row.dataset.id);$('teamStatus').textContent=error?'Remove error: '+error.message:'Player removed.';loadMembers()})})}
async function sendInvite(){const status=$('teamStatus');try{if(!captainTeam)return;const invitedEmail=$('inviteEmail').value.trim()||null,invitedUserId=$('inviteUserId').value.trim()||null,invitedRiotId=$('inviteRiot').value.trim()||null;if(!invitedEmail&&!invitedUserId&&!invitedRiotId){status.textContent='Enter an email, user ID, or Riot ID.';return}
const message=await supabase.from('player_messages').insert({recipient_user_id:invitedUserId,recipient_email:invitedEmail,sender_user_id:currentUser.id,message_type:'team_invite',title:`Invite to ${captainTeam.name}`,body:`You have been invited to join ${captainTeam.name} on VCC.`,related_team_id:captainTeam.id,status:'unread',action_url:'inbox.html'}).select().single();if(message.error)throw message.error;
const invite=await supabase.from('team_invites').insert({team_id:captainTeam.id,invited_user_id:invitedUserId,invited_email:invitedEmail,invited_riot_id:invitedRiotId,invited_by:currentUser.id,role:$('inviteRole').value,status:'pending',message_id:message.data.id});if(invite.error)throw invite.error;status.textContent='Invite sent.';$('inviteEmail').value='';$('inviteUserId').value='';$('inviteRiot').value=''}catch(err){status.textContent='Invite error: '+err.message}}
document.addEventListener('DOMContentLoaded',()=>{$('sendInviteBtn').addEventListener('click',sendInvite);loadCaptainTeam().catch(err=>{$('teamStatus').textContent='Access error: '+err.message;$('noTeamBox').style.display='block'})});