import { supabase } from './app.js';
const $=id=>document.getElementById(id);const params=new URLSearchParams(location.search);const requestedUserId=params.get('user')||params.get('id')||'';
function setText(id,v){const el=$(id);if(el)el.textContent=v??''}function setValue(id,v){const el=$(id);if(el)el.value=v||''}
async function getUser(){const s=await supabase.auth.getSession();return s?.data?.session?.user||null}
async function loadProfileById(id){const {data,error}=await supabase.from('profiles').select('*').eq('id',id).maybeSingle();if(error&&error.code!=='PGRST116')throw error;return data}
async function getCaptainTeam(userId){const {data}=await supabase.from('teams').select('*').eq('captain_id',userId).maybeSingle();return data}
function showPublic(){ $('editProfileControls')?.classList.add('hidden');$('editImageControls')?.classList.add('hidden');$('publicProfileView')?.classList.remove('hidden');$('messagesPanel')?.classList.add('hidden');$('profileTitle').textContent='VCC PLAYER PROFILE';$('profileModeNotice').textContent='Public view only. You cannot edit another player profile.'}
function showEdit(){ $('editProfileControls')?.classList.remove('hidden');$('editImageControls')?.classList.remove('hidden');$('publicProfileView')?.classList.add('hidden');$('messagesPanel')?.classList.remove('hidden');$('profileTitle').textContent='MY VCC PROFILE';$('profileModeNotice').textContent='You are editing your own profile.'}
function fillPublic(p){setText('publicName',p?.display_name||p?.username||'VCC Player');setText('publicRiot',p?.riot_id||'Not set');setText('publicRank',p?.rank||'Not set');setText('publicPlatform',p?.platform||'Not set');setText('publicRegion',p?.region||'Not set');setText('publicRole',p?.main_role||p?.role||'Not set');setText('publicAgents',p?.main_agents||'Not set');setText('publicBio',p?.bio||'No bio yet.');if(p?.avatar_url)$('profileAvatar').src=p.avatar_url;setText('winsText',p?.wins||0);setText('lossesText',p?.losses||0);setText('pointsText',p?.pro_points||0);setText('ratingText',p?.rating||1000);$('messageBtn').href=`message-player.html?${p?.id?'user='+encodeURIComponent(p.id):''}${p?.email?'&email='+encodeURIComponent(p.email):''}`}
function fillEdit(p){setValue('displayName',p?.display_name||p?.username||'');setValue('riotId',p?.riot_id||'');setValue('rank',p?.rank||'');setValue('platform',p?.platform||'');setValue('region',p?.region||'');setValue('mainRole',p?.main_role||p?.role||'');setValue('mainAgents',p?.main_agents||'');setValue('bio',p?.bio||'');if(p?.avatar_url)$('profileAvatar').src=p.avatar_url;setText('winsText',p?.wins||0);setText('lossesText',p?.losses||0);setText('pointsText',p?.pro_points||0);setText('ratingText',p?.rating||1000)}
async function ensureProfile(user){let p=await loadProfileById(user.id);if(p)return p;const username=user.email?user.email.split('@')[0]:'VCC Player';const {data,error}=await supabase.from('profiles').insert({id:user.id,email:user.email,username,display_name:username,updated_at:new Date().toISOString()}).select().single();if(error)throw error;return data}
async function addInviteButtonForPublic(viewedProfile,currentUser){const old=$('invitePlayerBtn');if(old)old.remove();const captainTeam=currentUser?await getCaptainTeam(currentUser.id):null;if(!captainTeam||!viewedProfile?.id||viewedProfile.id===currentUser.id)return;const btn=document.createElement('button');btn.id='invitePlayerBtn';btn.className='gold';btn.textContent='Invite To My Team';btn.addEventListener('click',async()=>{const msg=await supabase.from('player_messages').insert({recipient_user_id:viewedProfile.id,recipient_email:viewedProfile.email||null,sender_user_id:currentUser.id,message_type:'team_invite',title:`Invite to ${captainTeam.name}`,body:`You have been invited to join ${captainTeam.name} on VCC.`,related_team_id:captainTeam.id,status:'unread',action_url:'inbox.html'}).select().single();if(msg.error){$('profileStatus').textContent='Invite error: '+msg.error.message;return}const inv=await supabase.from('team_invites').insert({team_id:captainTeam.id,invited_user_id:viewedProfile.id,invited_email:viewedProfile.email||null,invited_by:currentUser.id,role:'player',status:'pending',message_id:msg.data.id});$('profileStatus').textContent=inv.error?'Invite error: '+inv.error.message:'Invite sent to player.'});$('messageBtn').after(btn)}
async function loadProfile(){const status=$('profileStatus');try{const user=await getUser();if(requestedUserId&&(!user||requestedUserId!==user.id)){showPublic();let p=await loadProfileById(requestedUserId);if(!p){p={id:requestedUserId,display_name:params.get('name'),riot_id:params.get('riot'),rank:params.get('rank'),platform:params.get('platform'),region:params.get('region'),main_role:params.get('role'),avatar_url:params.get('avatar')}}fillPublic(p);await addInviteButtonForPublic(p,user);status.textContent='Viewing public profile.';return}if(!user){showEdit();status.innerHTML='You are not logged in.<br><br><a class="btn" href="auth.html">Go to Login</a>';return}showEdit();const p=await ensureProfile(user);fillEdit(p);$('messageBtn').href=`message-player.html?user=${encodeURIComponent(user.id)}&email=${encodeURIComponent(user.email||'')}`;status.textContent='Logged in as '+(user.email||user.id)}catch(err){status.textContent='Profile error: '+err.message}}
async function saveProfile(){const status=$('profileStatus');try{const user=await getUser();if(!user){status.textContent='Log in first.';return}if(requestedUserId&&requestedUserId!==user.id){status.textContent='You cannot edit another player profile.';return}const displayName=$('displayName').value.trim();const patch={id:user.id,email:user.email,username:displayName||(user.email?user.email.split('@')[0]:'VCC Player'),display_name:displayName,riot_id:$('riotId').value.trim(),rank:$('rank').value.trim(),platform:$('platform').value.trim(),region:$('region').value.trim(),main_role:$('mainRole').value.trim(),role:$('mainRole').value.trim(),main_agents:$('mainAgents').value.trim(),bio:$('bio').value.trim(),updated_at:new Date().toISOString()};const {error}=await supabase.from('profiles').upsert(patch);if(error)throw error;status.textContent='Profile saved.'}catch(err){status.textContent='Save error: '+err.message}}
async function uploadAvatar(){const status=$('profileStatus');try{const user=await getUser();if(!user){status.textContent='Log in first.';return}const file=$('avatarFile').files[0];if(!file){status.textContent='Choose an image first.';return}const ext=file.name.split('.').pop();const path=`${user.id}/avatar.${ext}`;const up=await supabase.storage.from('profile-images').upload(path,file,{upsert:true});if(up.error)throw up.error;const url=supabase.storage.from('profile-images').getPublicUrl(path).data.publicUrl;const {error}=await supabase.from('profiles').upsert({id:user.id,email:user.email,avatar_url:url,updated_at:new Date().toISOString()});if(error)throw error;$('profileAvatar').src=url;status.textContent='Profile picture uploaded.'}catch(err){status.textContent='Upload error: '+err.message}}
document.addEventListener('DOMContentLoaded',()=>{$('saveProfileBtn')?.addEventListener('click',saveProfile);$('uploadAvatarBtn')?.addEventListener('click',uploadAvatar);$('avatarFile')?.addEventListener('change',()=>{const f=$('avatarFile').files[0];if(f)$('profileAvatar').src=URL.createObjectURL(f)});loadProfile()});