const VCC_TZ='America/Chicago';
const DEFAULT_DATA={
 tournaments:[{id:'season-zero',name:'VCC Season Zero',division:'Open',status:'Registration Open',format:'Open Qualifiers → Major → LCQ → Finals',startsAt:'2026-06-01T20:00',description:'First official VCC console Valorant season using Pro Points and playoff seeding.'}],
 matches:[{id:'VCC-S0-001',tournamentId:'season-zero',teamA:'Team A',teamB:'Team B',round:'Open Qualifier Round 1',scheduledAt:'2026-06-01T20:00',status:'Scheduled',server:'TBD',map:'TBD',scoreA:'',scoreB:'',winner:''}],
 chat:{},veto:{}
};
function vccLoad(){let d=localStorage.getItem('vcc_ops_data');if(!d){localStorage.setItem('vcc_ops_data',JSON.stringify(DEFAULT_DATA));return structuredClone(DEFAULT_DATA)}try{return JSON.parse(d)}catch(e){return structuredClone(DEFAULT_DATA)}}
function vccSave(d){localStorage.setItem('vcc_ops_data',JSON.stringify(d))}
function vccId(prefix){return prefix+'-'+Math.random().toString(36).slice(2,8).toUpperCase()}
function fmtTime(v){if(!v)return 'TBD';try{return new Intl.DateTimeFormat([], {weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(v))}catch(e){return v}}
function isAdmin(){return localStorage.getItem('vcc_admin_unlocked')==='true'}
function unlockAdmin(){const code=document.getElementById('adminCode')?.value.trim(); if(code==='VCCADMIN' || code==='SINADMIN'){localStorage.setItem('vcc_admin_unlocked','true'); location.reload()} else alert('Wrong admin code. Default demo code is VCCADMIN. Change this before going public.')}
function logoutAdmin(){localStorage.removeItem('vcc_admin_unlocked');location.reload()}
function renderTournaments(){const el=document.getElementById('tournamentList'); if(!el)return; const d=vccLoad(); el.innerHTML=d.tournaments.map(t=>`<div class="tournament-card"><div class="match-head"><div><span class="pill gold">${t.status}</span><h3>${t.name}</h3><p>${t.description||''}</p><p class="muted"><b>Division:</b> ${t.division} · <b>Format:</b> ${t.format} · <b>Starts:</b> ${fmtTime(t.startsAt)}</p></div><a class="btn primary" href="matches.html?tournament=${t.id}">View Matches</a></div></div>`).join('')||'<p>No tournaments yet.</p>'}
function renderMatches(){const el=document.getElementById('matchList'); if(!el)return; const d=vccLoad(); const q=new URLSearchParams(location.search); const filter=q.get('tournament'); let matches=d.matches.filter(m=>!filter||m.tournamentId===filter); el.innerHTML=matches.map(m=>`<div class="match-card"><div class="match-head"><div><span class="pill blue">${m.status}</span><div class="match-teams">${m.teamA} <span class="danger-text">vs</span> ${m.teamB}</div><p class="muted">${m.round} · ${m.id}</p><p><b>Time:</b> ${fmtTime(m.scheduledAt)} · <b>Server:</b> ${m.server||'TBD'} · <b>Map:</b> ${m.map||'TBD'}</p><p><b>Score:</b> ${m.scoreA||'-'} - ${m.scoreB||'-'} ${m.winner?`· <b>Winner:</b> ${m.winner}`:''}</p></div><div><a class="btn primary" href="match-room.html?id=${m.id}">Open Match Room</a></div></div></div>`).join('')||'<p>No matches yet.</p>'}
function adminInit(){const gate=document.getElementById('adminGate'), panel=document.getElementById('adminPanel'); if(!gate)return; if(!isAdmin()){gate.hidden=false; panel.hidden=true; return} gate.hidden=true; panel.hidden=false; renderAdminLists();}
function renderAdminLists(){const d=vccLoad(); const t=document.getElementById('adminTournaments'), m=document.getElementById('adminMatches'); if(t)t.innerHTML=d.tournaments.map(x=>`<div class="card"><b>${x.name}</b><p class="muted">${x.status} · ${x.division}</p><button class="btn danger" onclick="deleteTournament('${x.id}')">Delete</button></div>`).join(''); if(m)m.innerHTML=d.matches.map(x=>`<div class="card"><b>${x.teamA} vs ${x.teamB}</b><p class="muted">${x.round} · ${fmtTime(x.scheduledAt)}</p><button class="btn danger" onclick="deleteMatch('${x.id}')">Delete</button></div>`).join('')}
function addTournament(){const d=vccLoad(); d.tournaments.push({id:vccId('T'),name:val('tName'),division:val('tDivision'),status:val('tStatus'),format:val('tFormat'),startsAt:val('tStart'),description:val('tDesc')}); vccSave(d); location.reload()}
function addMatch(){const d=vccLoad(); d.matches.push({id:vccId('VCC'),tournamentId:val('mTournament')||d.tournaments[0]?.id,teamA:val('mA'),teamB:val('mB'),round:val('mRound'),scheduledAt:val('mTime'),status:'Scheduled',server:'TBD',map:'TBD',scoreA:'',scoreB:'',winner:''}); vccSave(d); location.reload()}
function updateResult(){const d=vccLoad(); const id=val('rMatch'); const m=d.matches.find(x=>x.id===id); if(!m)return alert('Match not found'); m.scoreA=val('rA'); m.scoreB=val('rB'); m.winner=val('rWinner'); m.status=val('rStatus')||'Completed'; vccSave(d); location.reload()}
function deleteTournament(id){let d=vccLoad(); d.tournaments=d.tournaments.filter(x=>x.id!==id); vccSave(d); location.reload()}
function deleteMatch(id){let d=vccLoad(); d.matches=d.matches.filter(x=>x.id!==id); vccSave(d); location.reload()}
function val(id){return document.getElementById(id)?.value.trim()||''}
function roomInit(){const id=new URLSearchParams(location.search).get('id'); const d=vccLoad(); const m=d.matches.find(x=>x.id===id)||d.matches[0]; if(!m)return; document.getElementById('roomTitle').textContent=`${m.teamA} vs ${m.teamB}`; document.getElementById('roomMeta').textContent=`${m.round} · ${m.id} · ${fmtTime(m.scheduledAt)}`; document.getElementById('roomServer').textContent=m.server||'TBD'; document.getElementById('roomMap').textContent=m.map||'TBD'; document.getElementById('roomScore').textContent=`${m.scoreA||'-'} - ${m.scoreB||'-'}`; countdown(m.scheduledAt); renderChat(m.id); renderVeto(m.id); document.getElementById('chatSend').onclick=()=>sendChat(m.id); document.getElementById('saveVeto').onclick=()=>saveVeto(m.id); document.getElementById('submitRoomScore').onclick=()=>submitRoomScore(m.id);}
function countdown(t){const el=document.getElementById('countdown'); if(!el)return; function tick(){const diff=new Date(t)-new Date(); if(diff<=0){el.textContent='MATCH TIME';return} const h=Math.floor(diff/36e5), min=Math.floor(diff%36e5/6e4), s=Math.floor(diff%6e4/1e3); el.textContent=`${h}h ${min}m ${s}s`} tick(); setInterval(tick,1000)}
function renderChat(id){const d=vccLoad(); const el=document.getElementById('chatBox'); if(!el)return; const msgs=d.chat[id]||[]; el.innerHTML=msgs.map(x=>`<div class="chat-msg"><b>${x.name}</b><br>${x.msg}<br><span class="muted">${fmtTime(x.time)}</span></div>`).join('')||'<p class="muted">No messages yet.</p>'}
function sendChat(id){const name=val('chatName')||'Captain'; const msg=val('chatMsg'); if(!msg)return; const d=vccLoad(); d.chat[id]=d.chat[id]||[]; d.chat[id].push({name,msg,time:new Date().toISOString()}); vccSave(d); document.getElementById('chatMsg').value=''; renderChat(id)}
function renderVeto(id){const d=vccLoad(); const v=d.veto[id]||{}; const el=document.getElementById('vetoLog'); if(el)el.innerHTML=`<p><b>Map Ban/Pick:</b> ${v.map||'Not set'}</p><p><b>Server/Region:</b> ${v.server||'Not set'}</p><p class="muted">Use this for FACEIT/ESEA-style captain agreement.</p>`}
function saveVeto(id){const d=vccLoad(); d.veto[id]={map:val('vetoMap'),server:val('vetoServer')}; const m=d.matches.find(x=>x.id===id); if(m){m.map=val('vetoMap')||m.map;m.server=val('vetoServer')||m.server} vccSave(d); renderVeto(id); roomInit()}
function submitRoomScore(id){const d=vccLoad(); const m=d.matches.find(x=>x.id===id); if(!m)return; m.scoreA=val('scoreA'); m.scoreB=val('scoreB'); m.status='Pending Admin Approval'; vccSave(d); alert('Score submitted. Admin should verify screenshot/proof before marking completed.'); roomInit()}
document.addEventListener('DOMContentLoaded',()=>{renderTournaments();renderMatches();adminInit(); if(document.body.dataset.page==='room')roomInit(); const sel=document.getElementById('mTournament'); if(sel){const d=vccLoad(); sel.innerHTML=d.tournaments.map(t=>`<option value="${t.id}">${t.name}</option>`).join(''); document.getElementById('rMatch').innerHTML=d.matches.map(m=>`<option value="${m.id}">${m.teamA} vs ${m.teamB} — ${m.id}</option>`).join('')}});
